---
# tasks file for GestionGlassesRole
- name: Download & install docker script
  template:
    src: "docker_install.sh.j2"
    dest: "/home/{{ ansible_user }}/docker_install.sh"

- name: run script shell for install docker
  command: "sh /home/{{ ansible_user }}/docker_install.sh"

- name: start service docker
  service:
    name: docker
    state: started
    enabled: yes

- name: give the to ubuntu
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups:
      - docker

- name: Download & install docker-compose script
  template:
    src: "docker-compose_install.sh.j2"
    dest: "/home/{{ ansible_user }}/docker-compose_install.sh"

- name: run script shell for install  docker-compose
  command: "sh /home/{{ ansible_user }}/compose_install.sh"

