---
# tasks file for GestionGlassesRole
- name: Download & install docker script
  template:
    src: "docker_install.sh.j2"
    dest: "/home/{{ ansible_user }}/docker_install.sh"

- name: run script shell for install docker
  command: "sh /home/{{ ansible_user }}/docker_install.sh"

- name: start service docker
  service:
    name: docker
    state: started
    enabled: yes

- name: give the to ubuntu
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups:
      - docker
      
- name: check latest docker version
  set_fact:
    docker_compose_latest_version: "{{ lookup('url', 'https://github.com/docker/compose/releases/latest') | regex_findall('download/([0-9]+[.][0-9]+[.][0-9]+)') | first }}"
  when: docker_compose_version == 'latest'
  changed_when: false
- name: check installed docker compose version
  shell: "{{ docker_compose_bin }} --version | awk -F'[ ,]' '{ print $3; }' | grep {{ docker_compose_latest_version | default(docker_compose_version) }}"
  register: docker_compose_version_installed_result
  failed_when: false
  changed_when: false
- name: store installed docker compose version result
  set_fact:
    docker_compose_desired_version_installed: "{{ docker_compose_version_installed_result.rc == 0 }}"
- name: install docker-compose
  become: '{{ docker_compose_as_root }}'
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_latest_version | default(docker_compose_version) }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}'
    dest: '{{ docker_compose_bin }}'
    force: true
    mode: '555'
  when: not docker_compose_desired_version_installed
