---
# tasks file for GestionGlassesRole
- name: Download & install docker script
  template:
    src: "docker_install.sh.j2"
    dest: "/home/{{ ansible_user }}/docker_install.sh"

- name: run script shell for install docker
  command: "sh /home/{{ ansible_user }}/docker_install.sh"

- name: start service docker
  service:
    name: docker
    state: started
    enabled: yes

- name: give the to ubuntu
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups:
      - docker

- name: run shell for install docker-compose
  command: "sudo curl -L 'https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose"

- name: give the access to ubuntu for docker-compose
  command: "sudo chmod +x /usr/local/bin/docker-compose"
