---
- name: "Download data from git repo"
  git:
    repo: 'https://github.com/brikema/GestionGlasses.git'
    branch: devops
    dest: /home/{{ ansible_user }}/GestionGlasses

  # - name: copy docker-compose.yml
  #   copy:
  #     src: /home/{{ ansible_user }}/GestionGlasses
  #     dest: tmp/
  # - name: test docker-compose
  #   docker_compose:
  #     project_src: tmp/
  #     state: present
